net:
  target: ""
  port: 4444

data:
  dir: ""
  prefix: "testdata"
  postfix: ".json"

pc: ""
  #pc settings


rpi:
  #rpi settings
  GPIO:
    #functionality
      #valve
        #2way
        #3way
    valves:
      pressurize:
        pin: 5
      lox_vent:
        pin: 20
      kerosene_vent:
        pin: 21
      lox_dump:
        pin: 19
      kerosene_dump:
        pin: 22

    engine:
      enginestart_delay:
        time_ms: 1000
      igniter:
        pin:

    #pressure transducer i2c scheme addr -> i2c address, threshold <psi>
    pressure:
      sampling:
        ts: 0.01
      Kerosene:
        Threshold: 750
      RP1:
        Threshold: 750
      pt1:
        addr:
      pt2:
        addr:
      pt3:
        addr:
      pt4:
        addr:

  loadcell:
    #https://www.robotshop.com/media/files/pdf/phidgets-phidgetbridge-wheatstone-bridge-sensor-interface-w--enclosure-datasheet.pdf
    #phidget22 api doc for 1046 Bridge
    usb: "/dev/ttyUSB(Number here for usb device)"
    channel: 1
    serialnumber:
